insert into airlines (airline_name, iata_code) values ('Emirates', 'EK');
insert into airlines (airline_name, iata_code) values ('Air France', 'AF');
insert into airlines (airline_name, iata_code) values ('Air New Zealand', 'NZ');
insert into airlines (airline_name, iata_code) values ('South African Airways', 'SA');
insert into airlines (airline_name, iata_code) values ('Qatar Airways', 'QR');
insert into airlines (airline_name, iata_code) values ('Delta Air Lines', 'DL');
insert into airlines (airline_name, iata_code) values ('Avianca', 'AV');
insert into airlines (airline_name, iata_code) values ('Ethiopian Airlines', 'ET');
insert into airlines (airline_name, iata_code) values ('KLM Royal Dutch Airlines', 'KL');
insert into airlines (airline_name, iata_code) values ('Thai Airways', 'TG');
insert into airlines (airline_name, iata_code) values ('Southwest Airlines', 'WN');
insert into airlines (airline_name, iata_code) values ('United Airlines', 'UA');
insert into airlines (airline_name, iata_code) values ('Air India', 'AI');
insert into airlines (airline_name, iata_code) values ('Lufthansa', 'LH');
insert into airlines (airline_name, iata_code) values ('Singapore Airlines', 'SQ');
insert into airlines (airline_name, iata_code) values ('Qantas', 'QF');
insert into airlines (airline_name, iata_code) values ('American Airlines', 'AA');
insert into airlines (airline_name, iata_code) values ('Cathay Pacific', 'CX');
insert into airlines (airline_name, iata_code) values ('Aeroméxico', 'AM');
insert into airlines (airline_name, iata_code) values ('British Airways', 'BA');
insert into airlines (airline_name, iata_code) values ('Alitalia', 'AZ');
insert into airlines (airline_name, iata_code) values ('LATAM Airlines', 'LA');
insert into airlines (airline_name, iata_code) values ('SAS Scandinavian', 'SK');
insert into airlines (airline_name, iata_code) values ('Korean Air', 'KE');
insert into airlines (airline_name, iata_code) values ('Iberia', 'IB');
insert into airlines (airline_name, iata_code) values ('Air Canada', 'AC');
insert into airlines (airline_name, iata_code) values ('All Nippon Airways', 'NH');